-- ============================================
-- AI OPPORTUNITIES - SEED DATA
-- ============================================
-- Populates 20 pre-defined AI opportunities

-- Clear existing data (if re-running)
TRUNCATE TABLE ai_opportunities;

-- CATEGORY: CUSTOMER SERVICE (4 opportunities)

INSERT INTO ai_opportunities (opportunity_id, name, category, pain_question, description_short, description_detailed, business_value_1, business_value_2, business_value_3, business_value_4, primary_goals, value_priorities, cost_base, cost_range_display, timeline_weeks, timeline_display, roi_annual_base, roi_range_display, payback_months, complexity, budget_tier, deliverable_1, deliverable_2, deliverable_3, deliverable_4, deliverable_5, maintenance_annual, industry_fit) VALUES
('opp_customer_support_chatbot', 'AI-Powered Customer Support Assistant', 'Customer Service', 'Q5',
'Automated chatbot answers common customer questions 24/7, reducing support workload',
'Deploy an AI chatbot that handles 60-70% of customer inquiries automatically by searching your knowledge base and providing instant, accurate answers. Escalates complex issues to human agents seamlessly.',
'40-60% reduction in support ticket volume',
'24/7 customer support without hiring night shifts',
'2-5 minute average response time (vs 2-4 hours)',
'Frees up support team for complex issues',
'["Improve customer satisfaction / retention", "Reduce operational costs", "Scale operations without adding headcount"]',
'["Freeing up employee time for higher-value work", "Faster response times to customers"]',
25000, '$15K-$45K', 10, '8-12 weeks', 45000, '$30K-$120K/year', 7, 'Moderate', 2,
'Custom-trained AI chatbot',
'Integration with your knowledge base',
'Website and email channel deployment',
'Escalation workflow to human agents',
'Admin dashboard for monitoring',
5000, '["All industries", "Especially: SaaS, E-commerce, Professional Services"]'),

('opp_internal_knowledge_base', 'Internal Knowledge Base (Employee Self-Service)', 'Customer Service', 'Q9',
'AI-powered search helps employees find information instantly across all company documents',
'Create an intelligent knowledge base that employees can query in plain English to find policies, procedures, and past work examples. Reduces time wasted searching and asking colleagues for information.',
'Employees find information in seconds vs hours',
'Reduces interruptions to senior team members',
'Preserves institutional knowledge',
'Onboard new employees faster',
'["Improve team productivity", "Freeing up employee time for higher-value work"]',
'["Freeing up employee time for higher-value work"]',
30000, '$20K-$50K', 12, '10-14 weeks', 40000, '$25K-$80K/year', 9, 'Moderate', 3,
'Internal knowledge base with AI search',
'Document indexing and categorization',
'Slack/Teams integration',
'Employee training',
'Analytics dashboard',
4000, '["All industries", "Especially: Professional Services, Healthcare"]'),

('opp_email_response_automation', 'Email Response Automation', 'Customer Service', 'Q5',
'AI drafts responses to common customer emails, reducing response time',
'Automatically generates draft responses to incoming customer emails based on email content and your knowledge base. Support team reviews and sends with one click.',
'70-80% faster response times',
'Consistent, high-quality responses',
'Support team handles 3x more volume',
'Reduced training time for new support staff',
'["Faster response times to customers", "Improve team productivity"]',
'["Faster response times to customers", "Freeing up employee time for higher-value work"]',
18000, '$12K-$30K', 8, '6-10 weeks', 30000, '$20K-$60K/year', 7, 'Simple', 2,
'Email classification and routing',
'AI-powered draft generation',
'Integration with your email system',
'Quality control dashboard',
'Performance analytics',
3000, '["E-commerce", "SaaS", "Professional Services"]'),

('opp_multichannel_support_bot', 'Multi-Channel Support Bot (Website + Slack + Email)', 'Customer Service', 'Q5',
'Unified AI assistant across all customer communication channels',
'Single AI system that handles customer questions across website chat, Slack community, email, and internal help desk with consistent responses and full conversation history.',
'Omnichannel customer experience',
'Single system to train and maintain',
'Conversation history across channels',
'Reduced tool complexity',
'["Improve customer satisfaction / retention", "Scale operations without adding headcount"]',
'["Faster response times to customers"]',
45000, '$30K-$70K', 14, '12-16 weeks', 80000, '$50K-$150K/year', 7, 'Complex', 3,
'Multi-channel AI bot (web, Slack, email)',
'Unified conversation tracking',
'Advanced escalation workflows',
'Team collaboration features',
'Comprehensive analytics',
8000, '["SaaS", "Technology companies with online communities"]');

-- CATEGORY: CONTENT & MARKETING (5 opportunities)

INSERT INTO ai_opportunities (opportunity_id, name, category, pain_question, description_short, description_detailed, business_value_1, business_value_2, business_value_3, business_value_4, primary_goals, value_priorities, cost_base, cost_range_display, timeline_weeks, timeline_display, roi_annual_base, roi_range_display, payback_months, complexity, budget_tier, deliverable_1, deliverable_2, deliverable_3, deliverable_4, deliverable_5, maintenance_annual, industry_fit) VALUES
('opp_blog_content_generation', 'Automated Blog & Content Generation', 'Content & Marketing', 'Q6',
'AI generates blog posts, articles, and social content from topics or outlines',
'Transform keywords or outlines into full blog posts, social media content, and newsletters. AI matches your brand voice and includes SEO optimization. Humans review and publish.',
'10-15 blog posts per month vs 2-3',
'Consistent publishing schedule',
'SEO-optimized content',
'Frees marketing team for strategy',
'["Increase revenue / sales", "Improve team productivity"]',
'["Freeing up employee time for higher-value work"]',
20000, '$12K-$35K', 8, '6-10 weeks', 50000, '$30K-$100K/year', 5, 'Simple', 2,
'AI content generation system',
'Brand voice training',
'SEO optimization integration',
'Editorial workflow',
'Content calendar integration',
2000, '["Marketing/Agency", "Professional Services", "E-commerce"]'),

('opp_personalized_email_campaigns', 'Personalized Email Campaign Generator', 'Content & Marketing', 'Q6',
'AI creates personalized email sequences based on customer data and behavior',
'Generate customized email campaigns for different customer segments. AI personalizes subject lines, content, and CTAs based on customer data, purchase history, and engagement patterns.',
'3-5x higher open rates',
'2-4x higher click-through rates',
'Automated A/B testing',
'Scales to thousands of segments',
'["Increase revenue / sales", "Improve customer satisfaction / retention"]',
'["Freeing up employee time for higher-value work"]',
22000, '$15K-$40K', 10, '8-12 weeks', 60000, '$35K-$120K/year', 4, 'Moderate', 2,
'Email personalization engine',
'Segment-based automation',
'A/B testing framework',
'Integration with email platform',
'Performance analytics',
3000, '["E-commerce", "SaaS", "Professional Services"]'),

('opp_social_media_automation', 'Social Media Content Automation', 'Content & Marketing', 'Q6',
'AI generates social media posts from blog content, news, and company updates',
'Automatically create platform-optimized social posts from your blog content, industry news, or company announcements. Includes image suggestions, hashtags, and optimal posting times.',
'Save 10-15 hours/week on social media',
'Consistent posting schedule',
'Platform-optimized content',
'Increased engagement rates',
'["Improve team productivity", "Increase revenue / sales"]',
'["Freeing up employee time for higher-value work"]',
15000, '$10K-$25K', 6, '4-8 weeks', 35000, '$20K-$70K/year', 5, 'Simple', 1,
'Social media content generator',
'Multi-platform optimization',
'Scheduling integration',
'Brand voice consistency',
'Performance tracking',
1500, '["All industries"]'),

('opp_proposal_report_generator', 'Proposal & Report Generator', 'Content & Marketing', 'Q6',
'AI generates customized proposals and reports from templates and data',
'Create professional proposals, client reports, and presentations in minutes using AI. System pulls data from CRM, generates insights, and formats everything in your brand template.',
'10x faster proposal creation',
'Consistent quality and branding',
'Higher win rates from personalization',
'Sales team focuses on relationships, not paperwork',
'["Increase revenue / sales", "Improve team productivity"]',
'["Freeing up employee time for higher-value work", "Higher quality / consistency in deliverables"]',
28000, '$18K-$50K', 10, '8-12 weeks', 70000, '$40K-$140K/year', 5, 'Moderate', 2,
'Proposal generation system',
'CRM data integration',
'Template customization',
'Automated data visualization',
'Version control and approval workflow',
4000, '["Professional Services", "Consulting", "B2B Sales"]'),

('opp_product_description_generator', 'Product Description Generator (E-commerce)', 'Content & Marketing', 'Q6',
'AI writes product descriptions, titles, and metadata at scale',
'Generate SEO-optimized product descriptions, titles, and metadata for your entire catalog. AI adapts tone for different product categories and target audiences.',
'Write 100s of descriptions per day',
'Consistent quality and SEO',
'Multi-language support',
'A/B test descriptions automatically',
'["Scale operations without adding headcount", "Enter new markets / launch new products"]',
'["Freeing up employee time for higher-value work"]',
18000, '$12K-$30K', 8, '6-10 weeks', 45000, '$25K-$90K/year', 5, 'Simple', 2,
'Product description generation',
'SEO optimization engine',
'Multi-language support',
'Bulk processing capabilities',
'Quality control dashboard',
2500, '["E-commerce", "Retail", "Distributors"]');

-- CATEGORY: SALES & LEAD MANAGEMENT (4 opportunities)

INSERT INTO ai_opportunities (opportunity_id, name, category, pain_question, description_short, description_detailed, business_value_1, business_value_2, business_value_3, business_value_4, primary_goals, value_priorities, cost_base, cost_range_display, timeline_weeks, timeline_display, roi_annual_base, roi_range_display, payback_months, complexity, budget_tier, deliverable_1, deliverable_2, deliverable_3, deliverable_4, deliverable_5, maintenance_annual, industry_fit) VALUES
('opp_lead_qualification_scoring', 'AI Lead Qualification & Scoring', 'Sales & Lead Management', 'Q7',
'AI analyzes leads and scores them based on likelihood to convert',
'Automatically scores and qualifies inbound leads using demographic data, behavioral signals, and historical patterns. Prioritizes sales team focus on highest-potential opportunities.',
'Sales team focuses on best-fit leads',
'30-50% increase in conversion rates',
'Faster response to high-value leads',
'Data-driven lead routing',
'["Increase revenue / sales", "Improve team productivity"]',
'["Freeing up employee time for higher-value work", "Better data and insights for decisions"]',
25000, '$15K-$45K', 10, '8-12 weeks', 80000, '$45K-$150K/year', 4, 'Moderate', 2,
'Lead scoring model',
'CRM integration',
'Automated lead routing',
'Score explanation dashboard',
'Continuous model improvement',
4000, '["B2B Sales", "SaaS", "Professional Services"]'),

('opp_automated_lead_enrichment', 'Automated Lead Enrichment', 'Sales & Lead Management', 'Q7',
'AI automatically enriches lead records with company and contact data',
'Automatically research and enrich lead records with company size, revenue, tech stack, recent news, and decision-maker contacts. Eliminates manual research time.',
'Save 2-3 hours per lead on research',
'90%+ data accuracy',
'Real-time enrichment',
'Better targeting and personalization',
'["Increase revenue / sales", "Better data and insights for decisions"]',
'["Freeing up employee time for higher-value work"]',
20000, '$12K-$35K', 8, '6-10 weeks', 50000, '$30K-$100K/year', 5, 'Moderate', 2,
'Lead enrichment engine',
'CRM integration',
'Data quality monitoring',
'Automated updates',
'Compliance and privacy controls',
3000, '["B2B Sales", "SaaS"]'),

('opp_sales_followup_automation', 'Sales Follow-Up Automation', 'Sales & Lead Management', 'Q7',
'AI manages follow-up sequences and detects buying signals',
'Automatically sends personalized follow-up emails based on prospect behavior, detects buying signals, and alerts sales team when leads are hot. Never miss a follow-up.',
'Zero leads fall through cracks',
'3-5x more touches per lead',
'Respond to buying signals in minutes',
'Automated nurture for long sales cycles',
'["Increase revenue / sales", "Improve team productivity"]',
'["Freeing up employee time for higher-value work"]',
22000, '$15K-$40K', 8, '6-10 weeks', 65000, '$35K-$130K/year', 4, 'Simple', 2,
'Follow-up sequence automation',
'Buying signal detection',
'CRM and email integration',
'Performance analytics',
'A/B testing framework',
3500, '["B2B Sales", "High-ticket services"]'),

('opp_ai_crm_assistant', 'AI-Powered CRM Assistant (Data Entry + Insights)', 'Sales & Lead Management', 'Q7',
'AI automatically logs activities and surfaces insights from your CRM',
'Automatically capture emails, calls, and meetings in your CRM. AI generates deal summaries, next-step recommendations, and alerts for at-risk deals.',
'Eliminate manual CRM data entry',
'100% activity tracking',
'Proactive deal alerts',
'Coaching insights for sales managers',
'["Increase revenue / sales", "Better data and insights for decisions", "Improve team productivity"]',
'["Freeing up employee time for higher-value work", "Better data and insights for decisions"]',
35000, '$20K-$60K', 12, '10-14 weeks', 90000, '$50K-$180K/year', 5, 'Moderate', 3,
'CRM data capture automation',
'AI deal insights and forecasting',
'Email and calendar integration',
'Pipeline health monitoring',
'Manager coaching dashboard',
5000, '["B2B Sales", "Enterprise sales teams"]');

-- CATEGORY: OPERATIONS & AUTOMATION (4 opportunities)

INSERT INTO ai_opportunities (opportunity_id, name, category, pain_question, description_short, description_detailed, business_value_1, business_value_2, business_value_3, business_value_4, primary_goals, value_priorities, cost_base, cost_range_display, timeline_weeks, timeline_display, roi_annual_base, roi_range_display, payback_months, complexity, budget_tier, deliverable_1, deliverable_2, deliverable_3, deliverable_4, deliverable_5, maintenance_annual, industry_fit) VALUES
('opp_invoice_document_processing', 'Invoice & Document Processing Automation', 'Operations & Automation', 'Q8',
'AI extracts data from invoices, receipts, and documents automatically',
'Automatically process invoices, receipts, purchase orders, and contracts. AI extracts key data, validates against rules, routes for approval, and enters into your accounting system.',
'90-95% reduction in manual data entry',
'Same-day processing vs 3-5 days',
'Near-zero errors',
'Audit trail and compliance',
'["Reduce operational costs", "Improve team productivity"]',
'["Freeing up employee time for higher-value work"]',
25000, '$15K-$45K', 10, '8-12 weeks', 55000, '$30K-$110K/year', 5, 'Moderate', 2,
'Document processing AI',
'Accounting system integration',
'Approval workflow automation',
'Exception handling',
'Audit and compliance reporting',
4000, '["All industries with high document volume"]'),

('opp_contract_review_extraction', 'Contract Review & Data Extraction', 'Operations & Automation', 'Q8',
'AI reviews contracts and extracts key terms, dates, and obligations',
'Automatically review contracts, extract key clauses, dates, and obligations. Flag non-standard terms and populate your contract database. Reduce legal review time by 70%.',
'70-80% faster contract review',
'Catch risky clauses automatically',
'Searchable contract database',
'Proactive renewal reminders',
'["Reduce operational costs", "Higher quality / consistency in deliverables"]',
'["Freeing up employee time for higher-value work", "Higher quality / consistency in deliverables"]',
30000, '$18K-$55K', 12, '10-14 weeks', 70000, '$40K-$140K/year', 5, 'Moderate', 3,
'Contract analysis AI',
'Key term extraction',
'Risk flagging system',
'Contract database',
'Renewal tracking',
4500, '["Legal", "Real Estate", "Financial Services"]'),

('opp_workflow_automation', 'Workflow Automation (Multi-System Integration)', 'Operations & Automation', 'Q10',
'AI automates repetitive workflows across multiple systems',
'Connect your systems and automate repetitive workflows: lead to CRM, support ticket to project, order to fulfillment. Eliminate manual data copying and context switching.',
'Save 5-15 hours/week per employee',
'Zero manual data transfer errors',
'Real-time sync across systems',
'Process consistency',
'["Reduce operational costs", "Improve team productivity"]',
'["Freeing up employee time for higher-value work"]',
20000, '$12K-$35K', 8, '6-10 weeks', 45000, '$25K-$90K/year', 5, 'Simple', 2,
'Multi-system integration platform',
'Custom workflow builders',
'Error handling and monitoring',
'Pre-built connectors',
'Analytics dashboard',
3000, '["All industries"]'),

('opp_automated_report_generation', 'Automated Report Generation', 'Operations & Automation', 'Q10',
'AI generates business reports from data across multiple systems',
'Automatically generate weekly/monthly reports by pulling data from multiple systems, creating visualizations, and generating insights. No more manual spreadsheet work.',
'Reports in minutes vs hours',
'Always up-to-date data',
'Consistent formatting',
'Automatic insight generation',
'["Improve team productivity", "Better data and insights for decisions"]',
'["Freeing up employee time for higher-value work", "Better data and insights for decisions"]',
15000, '$8K-$25K', 6, '4-8 weeks', 30000, '$18K-$60K/year', 6, 'Simple', 1,
'Report automation engine',
'Data source integrations',
'Customizable templates',
'Automated distribution',
'Insight generation',
2000, '["All industries"]');

-- CATEGORY: STRATEGIC (3 opportunities)

INSERT INTO ai_opportunities (opportunity_id, name, category, pain_question, description_short, description_detailed, business_value_1, business_value_2, business_value_3, business_value_4, primary_goals, value_priorities, cost_base, cost_range_display, timeline_weeks, timeline_display, roi_annual_base, roi_range_display, payback_months, complexity, budget_tier, deliverable_1, deliverable_2, deliverable_3, deliverable_4, deliverable_5, maintenance_annual, industry_fit) VALUES
('opp_competitive_intelligence', 'Competitive Intelligence Monitor', 'Strategic', 'Q6',
'AI monitors competitors and surfaces strategic insights',
'Automatically track competitor websites, product launches, pricing changes, and news. AI generates weekly intelligence reports with strategic recommendations.',
'Stay ahead of competitive threats',
'Automated competitor monitoring',
'Strategic insights from data',
'Market trend identification',
'["Competitive advantage / innovation", "Better data and insights for decisions"]',
'["Better data and insights for decisions", "Competitive advantage / innovation"]',
22000, '$15K-$40K', 8, '6-10 weeks', 40000, '$25K-$80K/year', 7, 'Moderate', 2,
'Competitive monitoring system',
'Automated data collection',
'Weekly intelligence reports',
'Alert system for major changes',
'Trend analysis',
3000, '["All industries", "Especially competitive markets"]'),

('opp_customer_sentiment_analysis', 'Customer Sentiment Analysis Dashboard', 'Strategic', 'Q5',
'AI analyzes customer feedback and surfaces insights',
'Aggregate feedback from support tickets, reviews, surveys, and social media. AI identifies trends, sentiment shifts, and product improvement opportunities.',
'Identify issues before they escalate',
'Data-driven product decisions',
'Track sentiment over time',
'Competitive positioning insights',
'["Improve customer satisfaction / retention", "Better data and insights for decisions"]',
'["Better data and insights for decisions"]',
28000, '$18K-$50K', 10, '8-12 weeks', 50000, '$30K-$100K/year', 7, 'Moderate', 2,
'Sentiment analysis engine',
'Multi-source data aggregation',
'Trend identification',
'Executive dashboard',
'Automated alerts',
4000, '["SaaS", "E-commerce", "Consumer products"]'),

('opp_voice_of_customer_engine', 'Voice-of-Customer Insights Engine', 'Strategic', 'Q5',
'AI synthesizes all customer interactions into actionable insights',
'Comprehensive analysis of all customer touchpoints: calls, emails, chats, surveys. AI identifies common requests, pain points, and expansion opportunities. Feeds product and marketing strategy.',
'360-degree customer understanding',
'Prioritize product roadmap with data',
'Identify upsell opportunities',
'Reduce churn proactively',
'["Improve customer satisfaction / retention", "Competitive advantage / innovation", "Better data and insights for decisions"]',
'["Better data and insights for decisions"]',
35000, '$20K-$60K', 12, '10-14 weeks', 70000, '$40K-$140K/year', 6, 'Complex', 3,
'Multi-channel data aggregation',
'AI insight generation',
'Opportunity identification',
'Executive reporting',
'Integration with product/CRM tools',
5000, '["SaaS", "Professional Services", "B2B companies"]');
